import React from 'react';
import { Button, Table } from 'reactstrap';

export default function MyTable() {
  return (
    <Table
      borderless
    >
      <thead>
        <tr>
          <th>
            {' '}
            Итого
          </th>
          <th>
            9850
          </th>
          <th>
            340
          </th>
          <th>
            2450
          </th>
          <th>
            452
          </th>
          <th>
            2545
          </th>
          <th>
            5672
          </th>
          <th>
            85
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Образование
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>

        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Здравохранение
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>
        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Муниципальные учреждения
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>
        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Транспорт и логистика
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>
        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Силовые Структуры
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>
        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Жилые помещения
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>
        <tr>
          <th scope="row">
            <Button
              color="light"
              size="sm"
            >
              {'>'}
            </Button>
            Образование
          </th>
          <td>
            150
          </td>
          <td>
            10
          </td>
          <td>
            50
          </td>
          <td>
            12
          </td>
          <td>
            85
          </td>
          <td>
            100
          </td>
          <td>
            6
          </td>
        </tr>
      </tbody>
    </Table>
  );
}
